### ISSUE TITLE
Allow to download a zip file containing all the code for offline use, without Docker and no typescript/Webpack?

### ISSUE THREAD

**Issue by Naereen** [seamile/PyTutor#4]
Hi there,
First of all, thanks for keep this project here! [The author of PythonTutor](https://github.com/pgbovine/) has removed his [open-source version](https://github.com/pgbovine/OnlinePythonTutor/).

I would very much like to use this project on my own, but I would like to have the minimum work to do: no need for docker, and no need to install typescript/webpack and to install dependencies and compile everything.

I see that you have a live version running on <https://pytutor.seamile.cn/>.
Could you maybe provide a zip file containing the files of this working versions, here on GitHub in the "release" tab?
It would be very helpful!

Thanks in advance, regards from France, @Naereen

**Comment by Naereen** [comment]
Honestly the instructions from https://github.com/seamile/PyTutor/tree/master/v5-unity seems to be old and I bet it won't work easily, as the author wrote 
> ergh these instructions get outdated so quickly since the npm ecosystem is so unstable and moves so fast ...

So if you could provide this frozen snapshot of "production (minified, cache-busted) build for deployment", it would really be helpful!

**Comment by Naereen** [comment]
> [Just in case someone is interested by this script I wrote, to launch a local version of this fork](https://github.com/Naereen/bin/commit/190aebce869175e46654f62ee81108eff1725b5d). It works great, but only for Python 3 and no other languages... it's already something!

**Comment by seamile** [comment]
> Hi there,
> First of all, thanks for keep this project here! [The author of PythonTutor](https://github.com/pgbovine/) has removed his [open-source version](https://github.com/pgbovine/OnlinePythonTutor/).
> 
> I would very much like to use this project on my own, but I would like to have the minimum work to do: no need for docker, and no need to install typescript/webpack and to install dependencies and compile everything.
> 
> I see that you have a live version running on https://pytutor.seamile.cn/.
> Could you maybe provide a zip file containing the files of this working versions, here on GitHub in the "release" tab?
> It would be very helpful!
> 
> Thanks in advance, regards from France, @Naereen

<https://github.com/seamile/PyTutor/issues/6#issuecomment-792558975>

**Comment by seamile** [comment]
> Hi there,
> First of all, thanks for keep this project here! [The author of PythonTutor](https://github.com/pgbovine/) has removed his [open-source version](https://github.com/pgbovine/OnlinePythonTutor/).
> 
> I would very much like to use this project on my own, but I would like to have the minimum work to do: no need for docker, and no need to install typescript/webpack and to install dependencies and compile everything.
> 
> I see that you have a live version running on https://pytutor.seamile.cn/.
> Could you maybe provide a zip file containing the files of this working versions, here on GitHub in the "release" tab?
> It would be very helpful!
> 
> Thanks in advance, regards from France, @Naereen

Look here: <https://github.com/seamile/PyTutor/issues/6#issuecomment-792558975>

**Comment by Naereen** [comment]
Thanks for the reply.
For the Python backend, I have been able to use it locally, and it's quite easy as you said in https://github.com/seamile/PyTutor/issues/6#issuecomment-792558975
As for my other questions, I was more interested in getting a pre-compiled version of the other backends, especially the one for C programs.
But as you haven't deployed them, this question here is useless, I'm gonna close it.
Thanks anyway!
