### ISSUE TITLE
Not able to use other modes than Python (eg C) as HTTPS is forced on http://pytutor.seamile.cn

### ISSUE THREAD

**Issue by Naereen** [seamile/PyTutor#5]
Hi again,

When trying to use <https://pytutor.seamile.cn/c.html#mode=edit>, it refuses execution of non-python inputs if using HTTPS.
But <http://pytutor.seamile.cn/c.html#mode=edit> forces to go to HTTPS.

Could there be any work around?
Hosting it somewhere with HTTPS disabled?

Also related to https://github.com/seamile/PyTutor/issues/4, as if i'm able to run this locally (hopefully without docker), I can run it with pure HTTP and force to not have HTTPS.

Thanks!

**Comment by seamile** [comment]
I have turned off the automatic redirection of HTTPS. 
But the compilation environment for C programs is not installed in my container.
so I think you'd better test C code in <http://pythontutor.com/>

**Comment by Naereen** [comment]
Hello there,
Thanks for updating this setting, but indeed as you said, if there is only the Python environment in your installation, it's not only a question of turing off this HTTPS redirection.
Thanks for the reply!

**Comment by Naereen** [comment]
I wasn't looking for a second website to use to test C programs, as you said the official http://pythontutor.com/ works perfectly fine, but I was looking for someone who would have managed to compile and deploy the compilation backend for C programs.
Too bad you haven't tried or managed to do it, I would have liked to ask you for details about it!
