### ISSUE TITLE
How hard should it be to add support for another language like Python or C (OCaml)

### ISSUE THREAD

**Issue by Naereen** [seamile/PyTutor#6]
So here is what I tested so far, that lead to this question:

- using [tutormagic](https://github.com/kikocorreoso/tutormagic/), I can run C and Python code from a Jupyter notebook (perfect for teaching) that connects to http://PythonTutor.com ;
- it shouldn't be difficult to use another version of PythonTutor that would be running locally (this is where your PyTutor comes into place) ;
- so now if I imagine that I have a working local version of PyTutor, I would want to use it to teach another compiled/interpreted languages like C or Python... which is [OCaml](https://ocaml.org/). It is both interpreted and compiled, and from what I know, absolutely no tool has never been produced to allow visual debugging like what PythonTutor offers for C or Python...

And that's why I'm asking here this ticket: how hard should it be to add support for another language like Python or C (OCaml)?

What files would be required to change on the PythonTutor side, and what files / compiler / interpreter should be written for this new language?

Thanks in advance if you're interested and able to help me!
Cheers from France, @Naereen

**Comment by Naereen** [comment]
I would like to contact PythonTutor's author, but...
https://pg.ucsd.edu/#faq
> For Python Tutor, consult this doc and do not email me.

And he took down his version from GitHub, so... not a possiiblity.

**Comment by seamile** [comment]
Sorry, I don’t know much about OCaml.
I am a teacher. I forked this project just to facilitate teaching. Because access to [PythonTutor](http://pythontutor.com/) from our school is too slow.

If you want to run PyTutor locally, you only need to install `bottle` and run it like this:
```bash
$ pip install bottle
$ git clone https://github.com/seamile/PyTutor.git
$ cd ./PyTutor/v5-unity
$ python bottle_server.py
```
And then open the browser to visit `http://localhost:8003/visualize.html`.

Hope these can help you.
